### ISSUE TITLE
about coltran, I have some questions.

### ISSUE THREAD

**Issue by hufeng0912** [google-research/google-research#710] opened 2021-05-22 07:21 UTC
I have performed a grayscale image coloring test based on the pre-trained model you provided  @MechCoder**[(https://storage.cloud.google.com/gresearch/coltran/coltran.zip.)**] Why are the results all noisy images?
I have executed the custom_colorize.py in sequence according to the file description you provided.
![(2)](https://user-images.githubusercontent.com/50228574/119218090-1f5da100-bb11-11eb-97c6-5282b0e117f2.jpg)
![(3)](https://user-images.githubusercontent.com/50228574/119218091-208ece00-bb11-11eb-932b-b5e134c11079.jpg)
![(4)](https://user-images.githubusercontent.com/50228574/119218092-21276480-bb11-11eb-9907-9b0af0ffc843.jpg)
![(5)](https://user-images.githubusercontent.com/50228574/119218093-21bffb00-bb11-11eb-8c1c-cf5c1d755593.jpg)
![(6)](https://user-images.githubusercontent.com/50228574/119218094-21bffb00-bb11-11eb-8048-ffa3c26bf177.jpg)
![(7)](https://user-images.githubusercontent.com/50228574/119218095-22589180-bb11-11eb-8fdd-78d496dca7fc.jpg)
![(8)](https://user-images.githubusercontent.com/50228574/119218096-22f12800-bb11-11eb-96a1-ed3b8c73afb6.jpg)
![(9)](https://user-images.githubusercontent.com/50228574/119218097-22f12800-bb11-11eb-87f8-d07e0dc68f67.jpg)
![(10)](https://user-images.githubusercontent.com/50228574/119218098-2389be80-bb11-11eb-8a6f-0a78f16e12fd.jpg)
![(1)](https://user-images.githubusercontent.com/50228574/119218099-24225500-bb11-11eb-936f-b3dc8a180666.jpg)

**Comment by MechCoder** [comment] 2021-05-22 12:02
Hi, thanks for the interest in our paper

Are the checkpoints restored correctly? What is the output of this line?
https://github.com/google-research/google-research/blob/master/coltran/custom_colorize.py#L220

More generally, are these issues relevant?

https://github.com/google-research/google-research/issues/583
https://github.com/google-research/google-research/issues/619

**Comment by hufeng0912** [comment] 2021-05-22 12:13
Thank you very much for your quick reply。The following is my execution code command line：
```
python -m custom_colorize --config=coltran/configs/colorizer.py --logdir=coltran/coltran/colorizer --img_dir=coltran/test-qifengle --store_dir=coltran/results --mode=colorize

python -m custom_colorize --config=coltran/configs/color_upsampler.py --logdir=coltran/coltran/color_upsampler --img_dir=coltran/test-qifengle --store_dir=coltran/results --gen_data_dir=coltran/results/stage1 --mode=colorize

python -m custom_colorize --config=coltran/configs/spatial_upsampler.py --logdir=coltran/coltran/spatial_upsampler --img_dir=coltran/test-qifengle --store_dir=coltran/results --gen_data_dir=coltran/results/stage2 --mode=colorize
```
My test image is a grayscale image with a size of 256×256。
![(1)](https://user-images.githubusercontent.com/50228574/119226083-1e8d3500-bb3a-11eb-9307-369fb71462ee.jpg)
![(2)](https://user-images.githubusercontent.com/50228574/119226087-1fbe6200-bb3a-11eb-9b02-3e0a943d35b2.jpg)
![(3)](https://user-images.githubusercontent.com/50228574/119226090-20ef8f00-bb3a-11eb-8cb1-b0deb297bdf4.jpg)
![(4)](https://user-images.githubusercontent.com/50228574/119226091-21882580-bb3a-11eb-9328-f432daf0fe7b.jpg)
![(5)](https://user-images.githubusercontent.com/50228574/119226093-21882580-bb3a-11eb-92aa-ef005815bdab.jpg)
![(6)](https://user-images.githubusercontent.com/50228574/119226094-2220bc00-bb3a-11eb-8805-3f45e5e9f108.jpg)
![(7)](https://user-images.githubusercontent.com/50228574/119226095-22b95280-bb3a-11eb-88b9-8c4e3ce5cbd0.jpg)
![(8)](https://user-images.githubusercontent.com/50228574/119226098-22b95280-bb3a-11eb-8b55-bbb2d21af253.jpg)
![(9)](https://user-images.githubusercontent.com/50228574/119226099-2351e900-bb3a-11eb-8f7f-16d68d245bb5.jpg)
![(10)](https://user-images.githubusercontent.com/50228574/119226100-23ea7f80-bb3a-11eb-9428-d98d6c4b9286.jpg)
I have read all the questions from other users. At present, they are relevant, but you have provided a code that can be tested by inputting a grayscale image, right?
My second question is can I train my custom dataset? But from your code point of view, it is using the downloaded ImageNet dataset. Modify the custom dataset for your code, I still have no way to achieve it

**Comment by hufeng0912** [comment] 2021-05-22 12:17
By the way, the output result of this line in my impression is:
Producing sample after 301000 training steps

**Comment by hufeng0912** [comment] 2021-05-22 12:18
If your model is guaranteed to be valid, can it be tested with the grayscale input image I just provided?

**Comment by MechCoder** [comment] 2021-05-22 12:31
I converted some sample RGB test images from imagenet to grayscale images in a directory and the colorizer script colorized those images successfully (reproduced results from the paper).

Thanks for sharing your grayscale images. I will try to test your grayscale images using my setup later this week.

**Comment by hufeng0912** [comment] 2021-05-22 12:34
Thank you very much for your reply. The output on that line should be correct. But what I don’t understand is why the output result is a noise graph, because the GPU I use is Tesla v100

**Comment by MechCoder** [comment] 2021-05-22 13:00
Hmm, its weird that it is 301000 steps, I trained the colorizer model for 600K steps (https://tensorboard.dev/experiment/jrf7Og9oTeGEL2KrArQu6Q/#scalars&_smoothingWeight=0)

**Comment by hufeng0912** [comment] 2021-05-22 13:04
My client does not have permission to access this URL. Please confirm if I have downloaded your pre-trained model correctly
![image](https://user-images.githubusercontent.com/50228574/119227585-3d42fa00-bb41-11eb-8b80-b0994ab0ed38.png)
![image](https://user-images.githubusercontent.com/50228574/119227592-446a0800-bb41-11eb-8ab0-6225e928d5a4.png)
![image](https://user-images.githubusercontent.com/50228574/119227598-49c75280-bb41-11eb-82fe-4ae72bbc50d7.png)
![image](https://user-images.githubusercontent.com/50228574/119227606-5055ca00-bb41-11eb-9269-e53200cc95fe.png)

**Comment by MechCoder** [comment] 2021-05-22 13:09
Thanks! It looks fine to me.

Could you remove all the files from the store_dir and post the results from just the first line?

```
python -m custom_colorize --config=coltran/configs/colorizer.py --logdir=coltran/coltran/colorizer --img_dir=coltran/test-qifengle --store_dir=coltran/results --mode=colorize
```

**Comment by hufeng0912** [comment] 2021-05-22 13:16
Below is the result of using the first line of command：
According to your instructions, the output should be a 64×64 rough picture
![(1)](https://user-images.githubusercontent.com/50228574/119227907-e2120700-bb42-11eb-80f3-26f4c174be27.jpg)
![(2)](https://user-images.githubusercontent.com/50228574/119227910-e3433400-bb42-11eb-9295-ca45c02145d9.jpg)
![(3)](https://user-images.githubusercontent.com/50228574/119227911-e3433400-bb42-11eb-8e7f-032932dc7c60.jpg)
![(4)](https://user-images.githubusercontent.com/50228574/119227912-e3dbca80-bb42-11eb-9973-d07f274502f5.jpg)
![(5)](https://user-images.githubusercontent.com/50228574/119227913-e4746100-bb42-11eb-8e13-895b620cf62a.jpg)
![(6)](https://user-images.githubusercontent.com/50228574/119227914-e4746100-bb42-11eb-9625-d2d235867bd6.jpg)
![(7)](https://user-images.githubusercontent.com/50228574/119227915-e50cf780-bb42-11eb-9041-3752164361e5.jpg)
![(8)](https://user-images.githubusercontent.com/50228574/119227916-e5a58e00-bb42-11eb-95db-2050e2090f1d.jpg)
![(9)](https://user-images.githubusercontent.com/50228574/119227917-e5a58e00-bb42-11eb-991f-12d19c898bfc.jpg)
![(10)](https://user-images.githubusercontent.com/50228574/119227918-e63e2480-bb42-11eb-99a8-52177a77d7cc.jpg)

**Comment by MechCoder** [comment] 2021-05-22 13:59
I'm unable to reproduce your noisy images. I just tried the script on one of your grayscale images

![image](https://user-images.githubusercontent.com/1867024/119228937-bc223d80-bb15-11eb-9823-94a0b9f3115c.png)

and I get this output from the first command line:

![image](https://user-images.githubusercontent.com/1867024/119228965-d9efa280-bb15-11eb-971c-4694e9b2e9d2.png)

How are you storing the grayscale images in your directory?

**Comment by hufeng0912** [comment] 2021-05-22 14:43
I just put my grayscale images in the directory. And modify the path of custome_colorize code。 You sure the model of you performed are the same with the code of github？------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年5月22日(星期六) 晚上9:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [google-research/google-research] about coltran, I have some questions. (#710)

**Comment by MechCoder** [comment] 2021-05-22 15:32
Yes

![image](https://user-images.githubusercontent.com/1867024/119231907-60f74780-bb23-11eb-94fc-8b70cac2fef2.png)

Are your grayscale images stored as .jpg files?
Could you please post all the modifications you made to the code and also the output logs of your GPU?

Thanks!

**Comment by hufeng0912** [comment] 2021-05-22 15:52
Thank you for your reply. I will contact you tomorrow.------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年5月22日(星期六) 晚上11:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [google-research/google-research] about coltran, I have some questions. (#710)

**Comment by hufeng0912** [comment] 2021-05-23 06:21
YES，I just stored my grayscale images  as .jpg files.
and I never modify the code, I just modify the command.

**Comment by hufeng0912** [comment] 2021-05-23 06:43
now my gpu is RTX2080. Here is the out logs of the GPU after the first command:
`WARNING:tensorflow:From C:\Users\GLDYD-002\Anaconda3\envs\tensorflow2.0\lib\site-packages\tensorflow\python\training\moving_averages.py:444: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
W0523 14:24:35.690207 29252 deprecation.py:323] From C:\Users\GLDYD-002\Anaconda3\envs\tensorflow2.0\lib\site-packages\tensorflow\python\training\moving_averages.py:444: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
I0523 14:24:35.925577 29252 train_utils.py:91] Built with exponential moving average.
I0523 14:24:35.941554 29252 train_utils.py:185] Restoring from coltran/coltran/colorizer.
I0523 14:24:38.793386 29252 custom_colorize.py:220] Producing sample after 601000 training steps.
I0523 14:24:38.794382 29252 custom_colorize.py:223] 1
I0523 14:26:21.048899 29252 custom_colorize.py:245] ['(1).jpg', '(10).jpg', '(2).jpg', '(3).jpg', '(4).jpg', '(5).jpg', '(6).jpg', '(7).jpg', '(8).jpg', '(9).jpg']
I0523 14:26:21.051920 29252 custom_colorize.py:249] coltran/results\stage1\(1).jpg
I0523 14:26:21.051920 29252 custom_colorize.py:251] (64, 64, 3)
I0523 14:26:21.082807 29252 custom_colorize.py:249] coltran/results\stage1\(10).jpg
I0523 14:26:21.082807 29252 custom_colorize.py:251] (64, 64, 3)
I0523 14:26:21.110733 29252 custom_colorize.py:249] coltran/results\stage1\(2).jpg
I0523 14:26:21.110733 29252 custom_colorize.py:251] (64, 64, 3)
I0523 14:26:21.136664 29252 custom_colorize.py:249] coltran/results\stage1\(3).jpg
I0523 14:26:21.136664 29252 custom_colorize.py:251] (64, 64, 3)
I0523 14:26:21.160599 29252 custom_colorize.py:249] coltran/results\stage1\(4).jpg
I0523 14:26:21.161597 29252 custom_colorize.py:251] (64, 64, 3)
I0523 14:26:21.178551 29252 custom_colorize.py:249] coltran/results\stage1\(5).jpg
I0523 14:26:21.179549 29252 custom_colorize.py:251] (64, 64, 3)
I0523 14:26:21.202487 29252 custom_colorize.py:249] coltran/results\stage1\(6).jpg
I0523 14:26:21.202487 29252 custom_colorize.py:251] (64, 64, 3)
I0523 14:26:21.228418 29252 custom_colorize.py:249] coltran/results\stage1\(7).jpg
I0523 14:26:21.228418 29252 custom_colorize.py:251] (64, 64, 3)
I0523 14:26:21.252354 29252 custom_colorize.py:249] coltran/results\stage1\(8).jpg
I0523 14:26:21.253352 29252 custom_colorize.py:251] (64, 64, 3)
I0523 14:26:21.273298 29252 custom_colorize.py:249] coltran/results\stage1\(9).jpg
I0523 14:26:21.273298 29252 custom_colorize.py:251] (64, 64, 3)`

**Comment by MechCoder** [comment] 2021-05-23 10:10
I just made a new workspace and ran the commands again.  Here are my final colorized images.

![image](https://user-images.githubusercontent.com/1867024/119255848-25f62200-bbbe-11eb-8674-cc35eaa7e3b7.png)

![image](https://user-images.githubusercontent.com/1867024/119255857-31494d80-bbbe-11eb-9192-45d98f32a146.png)
![image](https://user-images.githubusercontent.com/1867024/119255869-3efed300-bbbe-11eb-9aca-31bd7076dbbb.png)
![image](https://user-images.githubusercontent.com/1867024/119255871-42925a00-bbbe-11eb-8cc8-0d5ff0eb0629.png)
![image](https://user-images.githubusercontent.com/1867024/119255884-50e07600-bbbe-11eb-900c-17dd505fc16b.png)
![image](https://user-images.githubusercontent.com/1867024/119255893-5dfd6500-bbbe-11eb-9c48-8dea6d9fcb3e.png)
![image](https://user-images.githubusercontent.com/1867024/119255910-6e154480-bbbe-11eb-85c7-85f97090b4f6.png)
![image](https://user-images.githubusercontent.com/1867024/119255915-72d9f880-bbbe-11eb-9800-9bf12dccc9b6.png)
![image](https://user-images.githubusercontent.com/1867024/119255921-75d4e900-bbbe-11eb-9ea8-c3bdd7000f81.png)
![image](https://user-images.githubusercontent.com/1867024/119255925-7bcaca00-bbbe-11eb-999f-132fcc64b1e7.png)

Unfortunately (or fortunately), I cannot reproduce any of your outputs, so it is difficult for me to offer help. 

1, Could you check if all flags are passed correctly
- For example, FLAGS.mode shoule be colorize in this line (https://github.com/google-research/google-research/blob/master/coltran/custom_colorize.py#L117)
- name should be 'coltran_core' in this line (https://github.com/google-research/google-research/blob/master/coltran/custom_colorize.py#L162)

2. Could you post your TF, NumPy and matplotlib versions?
3. Could you save the samples here (https://github.com/google-research/google-research/blob/master/coltran/custom_colorize.py#L250) as NumPy arrays? And then can you load the numpy arrays as images in a separate notebook to see if there is the same noisy output. I wonder if it has something to do with how matplotlib stores images.

**Comment by hufeng0912** [comment] 2021-05-23 10:21
Wow，your results are amazing！I will follow your advice to check the option，thanks for your help so much. We keep conversation later. ------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年5月23日(星期天) 晚上6:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [google-research/google-research] about coltran, I have some questions. (#710)

**Comment by hufeng0912** [comment] 2021-05-24 05:36
actually, I just modify the path of the custom_colorize.py, and others just keep original, Right?
and I don't find any error about the logs.

**Comment by MechCoder** [comment] 2021-05-24 06:03
Yeah those seem correct to me. I did not make any modifications from the script for the results I just posted.

**Comment by hufeng0912** [comment] 2021-05-24 06:34
my matplotlib versions is 3.4.1, numpy is 1.19.5, TF is 1.0.0.

**Comment by MechCoder** [comment] 2021-05-24 06:48
Your tensorflow version is outdated. I trained my models with 2.6.0. Could you update to Tensorflow 2.6.0 and report your results again?

**Comment by hufeng0912** [comment] 2021-05-24 06:51
ok, I will try it later. Thanks！

**Comment by hufeng0912** [comment] 2021-05-24 07:56
Thank you so much for your help! I try it again for the new version, here is my result after the first command:
![(1)](https://user-images.githubusercontent.com/50228574/119315504-7fd31680-bca8-11eb-98d6-e116e38d8bc2.jpg)
![(2)](https://user-images.githubusercontent.com/50228574/119315511-81044380-bca8-11eb-97b2-545a238c665f.jpg)
![(3)](https://user-images.githubusercontent.com/50228574/119315514-81044380-bca8-11eb-82a3-655225b800c3.jpg)
![(4)](https://user-images.githubusercontent.com/50228574/119315516-819cda00-bca8-11eb-8f13-36b561074969.jpg)
![(5)](https://user-images.githubusercontent.com/50228574/119315520-82357080-bca8-11eb-9e0d-a3f56e71e96e.jpg)
![(6)](https://user-images.githubusercontent.com/50228574/119315521-82357080-bca8-11eb-99ff-8a173aa03ee9.jpg)
![(7)](https://user-images.githubusercontent.com/50228574/119315524-82ce0700-bca8-11eb-9a3f-ed231004bed0.jpg)
![(8)](https://user-images.githubusercontent.com/50228574/119315527-83669d80-bca8-11eb-9896-5ab80506820c.jpg)
![(9)](https://user-images.githubusercontent.com/50228574/119315530-83669d80-bca8-11eb-8216-428b203b91e4.jpg)
![(10)](https://user-images.githubusercontent.com/50228574/119315533-83ff3400-bca8-11eb-8087-c7f9b89b9c2a.jpg)
I think it is the correct result for your codes, right?

**Comment by MechCoder** [comment] 2021-05-24 13:31
Yes indeed, they are as expected. Could you please close the issue if it is resolved?

**Closed** 2021-05-24 14:12 UTC

**Comment by MechCoder** [comment] 2021-05-24 14:13
@hufeng0912 I just pushed https://github.com/google-research/google-research/commit/c1c89f282cf6afaa6b07bebc2e3e3ed53fba5827 this which ensures that the TF version is greater than 2.6.0 and it automatically closed the issue. Feel free to let me know if you have other questions.

**Comment by hufeng0912** [comment] 2021-05-24 14:22
Ok，thanks for your help！------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年5月24日(星期一) 晚上10:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [google-research/google-research] about coltran, I have some questions. (#710)

**Comment by ketan-lambat** [comment] 2021-06-21 03:14
Can someone please provide me with a link to install Tensorflow version greater than 2.6.
I get this error (see attached img) when installing packages in Google Colab notebook.
With the default TF 2.5, I got a similar noise output as mentioned above.

@hufeng0912  Can you please let me know how and where did you run this code, (https://github.com/google-research/google-research/issues/710#issuecomment-846851319), particularly with the TensorFlow version.

@MechCoder Is it possible to train ColTran on a custom dataset?

![image](https://user-images.githubusercontent.com/42700922/122702000-1ecd3d00-d26c-11eb-8d9d-5b0810661d16.png)

**Comment by MechCoder** [comment] 2021-06-21 06:34
@ketan-lambat Could you verify that your TensorFlow version is indeed 2.5? @hufeng0912 reports the TF version of their version to be 1.1.0. 

Could you also verify that your checkpoints are restored correctly?, i.e the output of this line? (https://github.com/google-research/google-research/blob/master/coltran/custom_colorize.py#L220).

It should be possible to train/finetune on a custom dataset using functions over  https://github.com/google-research/google-research/blob/master/coltran/custom_colorize.py#L220 and https://github.com/google-research/google-research/blob/master/coltran/datasets.py but I did not have the time to pack them into a script.

**Comment by ketan-lambat** [comment] 2021-06-22 17:14
Found my Mistake
I did not specify the checkpoints in the command properly. 
I used [this](https://github.com/google-research/google-research/blob/a6fb1bd26b296510134f6f430a6e74743469ccb7/coltran/custom_colorize.py#L23-L35), but did not enter step specific checkpoint directory.

The correct command should include 

`--logdir=coltran/checkpoints/coltran/colorizer`
`--logdir=coltran/checkpoints/coltran/color_upsampler`
`--logdir=coltran/checkpoints/coltran/spatial_upsampler`
for each of the different steps.

I earlier had
```python
LOGDIR = 'coltran/checkpoints/coltran'
# and in command
--logdir=$LOGDIR
```
and it showed 0 training steps.

Yes, TF version is 2.5.
![image](https://user-images.githubusercontent.com/42700922/122968500-3b22c400-d3a9-11eb-88ff-7173c90f07a3.png)

I will check with the custom dataset train part.
Thanks.

**Comment by MechCoder** [comment] 2021-06-22 20:46
Great, I fixed the checkpoint paths in the documentation here (https://github.com/google-research/google-research/commit/51d533ef66e8486b0012b469a70d42bb8c53c67b)

**Comment by ketan-lambat** [comment] 2021-06-23 02:51
One more thing, why is there an extra `--` on [this line](https://github.com/google-research/google-research/blob/a6fb1bd26b296510134f6f430a6e74743469ccb7/coltran/custom_colorize.py#L33)  (and others steps too)?
```python
python -m coltran.custom_colorize -- --config=configs/colorizer.py \
``` 
For me, it gave some errors, which were resolved after removing them.

**Comment by MechCoder** [comment] 2021-06-23 20:16
fixed (https://github.com/google-research/google-research/commit/f753c392312d4ca1437f80dc9592b6c1461e63a0)

**Comment by MechCoder** [comment] 2021-07-11 10:01
I added support for training and finetuneing on custom datasets. You can set the FLAGS dataset=custom and data_dir to be a directory containing RGB images.

See: db430ca

If you are using the same resolutions as in our paper, finetuneing is recommended. You can set pretrain_dir to be a pretrained ImageNet (colorizer/upsampler) checkpoint.

**Comment by afefbnsaid** [comment] 2022-02-03 11:32
> python -m custom_colorize --config=coltran/configs/colorizer.py --logdir=coltran/coltran/colorizer --img_dir=coltran/test-qifengle --store_dir=coltran/results --mode=colorize



> 

how can you resize it !!
